// Paradox Panic - Statement Pools (split from config.js for line limit)
const TRUE_TEMPLATES = [
  () => { const n = 2 + Math.floor(Math.random() * 8); const m = 2 + Math.floor(Math.random() * 8); return `${n} + ${m} = ${n + m}`; },
  () => { const n = 2 + Math.floor(Math.random() * 12); const m = 2 + Math.floor(Math.random() * 12); return `${n} x ${m} = ${n * m}`; },
  () => { const n = 10 + Math.floor(Math.random() * 90); return `${n} is ${n % 2 === 0 ? 'an even' : 'an odd'} number`; },
  () => { const n = 2 + Math.floor(Math.random() * 20); return `${n * n} is the square of ${n}`; },
  () => 'Water freezes at 0 degrees Celsius',
  () => 'The Earth orbits the Sun',
  () => 'Humans have 46 chromosomes',
  () => 'Sound travels faster in water than in air',
  () => 'Light travels faster than sound',
  () => 'The Moon orbits the Earth',
  () => 'Diamond is harder than glass',
  () => 'Gold is a chemical element',
  () => 'Oxygen is needed for combustion',
  () => 'Mars has two moons',
  () => 'Venus is the hottest planet in our solar system',
  () => 'An octagon has 8 sides',
  () => 'A triangle has 3 angles',
  () => 'The Pacific is the largest ocean',
  () => 'Sharks are fish',
  () => 'Bats are mammals',
  () => 'Spiders have 8 legs',
  () => 'Mercury is the closest planet to the Sun',
  () => 'DNA stands for deoxyribonucleic acid',
  () => 'Helium is lighter than air',
  () => 'Iron is attracted to magnets',
  () => 'The speed of light is about 300,000 km/s',
  () => 'A year on Earth is about 365 days',
  () => 'Adult humans typically have 32 teeth',
  () => 'The Sahara is in Africa',
  () => 'Penguins cannot fly',
  () => 'Tokyo is in Japan',
  () => 'Pi is approximately 3.14159',
  () => { const n = 1 + Math.floor(Math.random() * 10); return `${n} cubed is ${n*n*n}`; },
  () => 'A hexagon has 6 sides',
  () => 'Water is composed of hydrogen and oxygen',
  () => 'The human heart has four chambers',
  () => 'Jupiter is the largest planet in our solar system',
  () => 'Whales are mammals, not fish',
  () => 'The boiling point of water at sea level is 100 C',
  () => 'A kilometer is longer than a mile... wait, no. A mile is longer than a kilometer',
];

const FALSE_TEMPLATES = [
  () => { const n = 2 + Math.floor(Math.random() * 8); const m = 2 + Math.floor(Math.random() * 8); const wrong = n + m + (1 + Math.floor(Math.random() * 5)); return `${n} + ${m} = ${wrong}`; },
  () => { const n = 2 + Math.floor(Math.random() * 12); const m = 2 + Math.floor(Math.random() * 12); const wrong = n * m + (1 + Math.floor(Math.random() * 10)); return `${n} x ${m} = ${wrong}`; },
  () => { const n = 10 + Math.floor(Math.random() * 90); return `${n} is ${n % 2 === 0 ? 'an odd' : 'an even'} number`; },
  () => 'Water freezes at 10 degrees Celsius',
  () => 'The Sun orbits the Earth',
  () => 'Humans have 48 chromosomes',
  () => 'Sound travels faster than light',
  () => 'The Moon is larger than the Earth',
  () => 'Diamonds are softer than wood',
  () => 'Mars has five moons',
  () => 'Mercury is the hottest planet in our solar system',
  () => 'A pentagon has 6 sides',
  () => 'Spiders have 6 legs',
  () => 'Whales are reptiles',
  () => 'The Atlantic is the largest ocean',
  () => 'Penguins can fly long distances',
  () => 'Tokyo is the capital of China',
  () => 'Pi is approximately 3.2',
  () => 'An octagon has 6 sides',
  () => 'Iron is repelled by magnets',
  () => 'Helium is heavier than lead',
  () => 'Adult humans typically have 28 teeth',
  () => 'The Sahara is in South America',
  () => 'Jupiter is the smallest planet',
  () => 'A year on Earth is about 400 days',
  () => 'The speed of light is about 3,000 km/s',
  () => 'Oxygen makes up 78% of the atmosphere',
  () => 'Gold is a liquid at room temperature',
  () => 'A triangle has 4 angles',
  () => 'DNA stands for deoxyribose nucleic alcohol',
  () => { const n = 2 + Math.floor(Math.random() * 10); return `The square root of ${n*n} is ${n+1}`; },
  () => 'Venus is the coldest planet in our solar system',
  () => 'Bats are birds',
  () => 'Sharks are mammals',
  () => 'The human heart has two chambers',
  () => 'Water is composed of hydrogen and carbon',
  () => 'The boiling point of water at sea level is 80 C',
  () => 'The Amazon River is in Europe',
  () => 'Neptune is closest to the Sun',
  () => 'Elephants are the smallest land mammals',
];

const PARADOX_POOL = [
  // Stage 1 unlocks (always available)
  { text: 'This statement is false', unlockStage: 0 },
  { text: 'I am lying right now', unlockStage: 0 },
  { text: 'The next statement is true. The previous statement is false.', unlockStage: 0 },
  { text: 'This sentence has never been thought by anyone', unlockStage: 0 },
  // Stage 5 unlocks
  { text: 'The set of all sets that do not contain themselves', unlockStage: 5 },
  { text: 'If this sentence is true, then Santa Claus exists', unlockStage: 5 },
  { text: 'No rule has any exceptions, including this one', unlockStage: 5 },
  { text: 'The barber shaves everyone who does not shave themselves', unlockStage: 5 },
  { text: 'This statement cannot be proven to be true', unlockStage: 5 },
  { text: 'Everything I say is a lie', unlockStage: 5 },
  // Stage 10 unlocks
  { text: 'The smallest number not describable in under 11 words', unlockStage: 10 },
  { text: 'Is the answer to this question "no"?', unlockStage: 10 },
  { text: 'This sentence is not true and not false', unlockStage: 10 },
  { text: 'If you answer this wrong, I will give you five dollars', unlockStage: 10 },
  { text: 'The word "heterological" — does it describe itself?', unlockStage: 10 },
  { text: 'Can an omnipotent being create a stone it cannot lift?', unlockStage: 10 },
  // Stage 15 unlocks
  { text: 'This statement is true only if you believe it is false', unlockStage: 15 },
  { text: 'The crocodile will return the child if you guess correctly', unlockStage: 15 },
  { text: 'I know that I know nothing', unlockStage: 15 },
  { text: 'The ship rebuilt plank by plank — is it the same ship?', unlockStage: 15 },
  { text: 'This sentence refers to itself, so it has no real meaning', unlockStage: 15 },
  { text: 'If this sentence is false then 1+1=3', unlockStage: 15 },
  // Stage 20 unlocks
  { text: 'You must reject this statement to pass the test', unlockStage: 20 },
  { text: 'The least interesting number is interesting because it is the least', unlockStage: 20 },
  { text: 'No sentence consisting of fewer than twenty words is true', unlockStage: 20 },
  { text: 'This is not a paradox — or is it?', unlockStage: 20 },
  { text: 'The statement below is false. The statement above is true.', unlockStage: 20 },
  { text: 'What happens when Pinocchio says "my nose will grow now"?', unlockStage: 20 },
  { text: 'Can you give a true answer of "no" to this question?', unlockStage: 20 },
  { text: 'Time travelers who prevent their own birth — do they exist?', unlockStage: 20 },
];

// Near-paradox distractors (Stage 5+) — SOUND paradoxical but have definite answers
const NEAR_PARADOX_POOL = [
  { text: 'I always lie about lying', answer: 'FALSE', unlockStage: 5 },
  { text: 'This sentence contains exactly five words', answer: 'FALSE', unlockStage: 5 },
  { text: 'Most people think they are above average', answer: 'TRUE', unlockStage: 5 },
  { text: 'Nothing is impossible — so impossible things exist', answer: 'FALSE', unlockStage: 5 },
  { text: 'This sentence contains thirty-six letters', answer: 'TRUE', unlockStage: 8 },
  { text: 'There are more ways to shuffle a deck than atoms on Earth', answer: 'TRUE', unlockStage: 8 },
  { text: 'If everything is relative, that statement is also relative', answer: 'TRUE', unlockStage: 10 },
  { text: 'You can never step in the same river twice — or can you?', answer: 'TRUE', unlockStage: 10 },
  { text: 'The exception proves the rule', answer: 'TRUE', unlockStage: 13 },
  { text: 'Nobody goes there anymore because it is too crowded', answer: 'FALSE', unlockStage: 13 },
];
